//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhataFlow.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KhataFlow.Core.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text provided..
        /// </summary>
        public static string Ai_Receipt_NoTextProvided {
            get {
                return ResourceManager.GetString("Ai.Receipt.NoTextProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text parsed successfully..
        /// </summary>
        public static string Ai_Receipt_ParsedSuccessfully {
            get {
                return ResourceManager.GetString("Ai.Receipt.ParsedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process input..
        /// </summary>
        public static string Ai_Receipt_ProcessingFailed {
            get {
                return ResourceManager.GetString("Ai.Receipt.ProcessingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file too large..
        /// </summary>
        public static string Ai_Voice_AudioTooLarge {
            get {
                return ResourceManager.GetString("Ai.Voice.AudioTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command processed..
        /// </summary>
        public static string Ai_Voice_CommandProcessed {
            get {
                return ResourceManager.GetString("Ai.Voice.CommandProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process command..
        /// </summary>
        public static string Ai_Voice_CommandProcessingFailed {
            get {
                return ResourceManager.GetString("Ai.Voice.CommandProcessingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio file received..
        /// </summary>
        public static string Ai_Voice_NoAudioReceived {
            get {
                return ResourceManager.GetString("Ai.Voice.NoAudioReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link will expire in 1 hour..
        /// </summary>
        public static string Auth_Email_ResetExpiry {
            get {
                return ResourceManager.GetString("Auth.Email.ResetExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string Auth_Email_ResetHeading {
            get {
                return ResourceManager.GetString("Auth.Email.ResetHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the link below to reset your password:.
        /// </summary>
        public static string Auth_Email_ResetInstruction {
            get {
                return ResourceManager.GetString("Auth.Email.ResetInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Auth_Email_ResetLinkText {
            get {
                return ResourceManager.GetString("Auth.Email.ResetLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        public static string Auth_Email_ResetSubject {
            get {
                return ResourceManager.GetString("Auth.Email.ResetSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If that email is registered, a reset link has been sent..
        /// </summary>
        public static string Auth_ForgotPassword_LinkSent {
            get {
                return ResourceManager.GetString("Auth.ForgotPassword.LinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string Auth_Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth.Login.InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful..
        /// </summary>
        public static string Auth_Login_Success {
            get {
                return ResourceManager.GetString("Auth.Login.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out successfully..
        /// </summary>
        public static string Auth_Logout_Success {
            get {
                return ResourceManager.GetString("Auth.Logout.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User identity could not be resolved..
        /// </summary>
        public static string Auth_Logout_UserIdentityUnresolved {
            get {
                return ResourceManager.GetString("Auth.Logout.UserIdentityUnresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token refreshed successfully..
        /// </summary>
        public static string Auth_Refresh_Success {
            get {
                return ResourceManager.GetString("Auth.Refresh.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created successfully..
        /// </summary>
        public static string Auth_Register_Success {
            get {
                return ResourceManager.GetString("Auth.Register.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        public static string Auth_ResetPassword_InvalidRequest {
            get {
                return ResourceManager.GetString("Auth.ResetPassword.InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully..
        /// </summary>
        public static string Auth_ResetPassword_Success {
            get {
                return ResourceManager.GetString("Auth.ResetPassword.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User identity could not be determined..
        /// </summary>
        public static string Auth_UserIdentity_Undetermined {
            get {
                return ResourceManager.GetString("Auth.UserIdentity.Undetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription changed successfully..
        /// </summary>
        public static string Business_ChangeSubscription_Success {
            get {
                return ResourceManager.GetString("Business.ChangeSubscription.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business created successfully..
        /// </summary>
        public static string Business_Create_Success {
            get {
                return ResourceManager.GetString("Business.Create.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Businesses retrieved successfully..
        /// </summary>
        public static string Business_GetAll_Success {
            get {
                return ResourceManager.GetString("Business.GetAll.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business not found..
        /// </summary>
        public static string Business_GetById_NotFound {
            get {
                return ResourceManager.GetString("Business.GetById.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business retrieved successfully..
        /// </summary>
        public static string Business_GetById_Success {
            get {
                return ResourceManager.GetString("Business.GetById.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impersonation token generated successfully..
        /// </summary>
        public static string Business_Impersonation_Success {
            get {
                return ResourceManager.GetString("Business.Impersonation.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No business found for this account. Please create a business before performing this action..
        /// </summary>
        public static string Business_NotFoundForAccount {
            get {
                return ResourceManager.GetString("Business.NotFoundForAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform summary retrieved successfully..
        /// </summary>
        public static string Business_PlatformSummary_Success {
            get {
                return ResourceManager.GetString("Business.PlatformSummary.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reactivate business..
        /// </summary>
        public static string Business_Reactivate_Failed {
            get {
                return ResourceManager.GetString("Business.Reactivate.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business reactivated successfully..
        /// </summary>
        public static string Business_Reactivate_Success {
            get {
                return ResourceManager.GetString("Business.Reactivate.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription renewed successfully..
        /// </summary>
        public static string Business_RenewSubscription_Success {
            get {
                return ResourceManager.GetString("Business.RenewSubscription.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to suspend business..
        /// </summary>
        public static string Business_Suspend_Failed {
            get {
                return ResourceManager.GetString("Business.Suspend.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business suspended successfully..
        /// </summary>
        public static string Business_Suspend_Success {
            get {
                return ResourceManager.GetString("Business.Suspend.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID mismatch..
        /// </summary>
        public static string Business_Update_IdMismatch {
            get {
                return ResourceManager.GetString("Business.Update.IdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business updated successfully..
        /// </summary>
        public static string Business_Update_Success {
            get {
                return ResourceManager.GetString("Business.Update.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient stock for product &apos;{0}&apos;..
        /// </summary>
        public static string Domain_Product_InsufficientStock {
            get {
                return ResourceManager.GetString("Domain.Product.InsufficientStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restock quantity must be greater than zero..
        /// </summary>
        public static string Domain_Product_RestockQuantity_GreaterThanZero {
            get {
                return ResourceManager.GetString("Domain.Product.RestockQuantity.GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed..
        /// </summary>
        public static string General_ValidationFailed {
            get {
                return ResourceManager.GetString("General.ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale &apos;{0}&apos; not found..
        /// </summary>
        public static string Invoice_Sale_NotFound {
            get {
                return ResourceManager.GetString("Invoice.Sale.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udhar added successfully..
        /// </summary>
        public static string Ledger_AddUdhar_Success {
            get {
                return ResourceManager.GetString("Ledger.AddUdhar.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route customerId and body CustomerId do not match..
        /// </summary>
        public static string Ledger_CustomerId_Mismatch {
            get {
                return ResourceManager.GetString("Ledger.CustomerId.Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khata retrieved successfully..
        /// </summary>
        public static string Ledger_GetKhata_Success {
            get {
                return ResourceManager.GetString("Ledger.GetKhata.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment recorded successfully..
        /// </summary>
        public static string Ledger_RecordPayment_Success {
            get {
                return ResourceManager.GetString("Ledger.RecordPayment.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification deleted successfully..
        /// </summary>
        public static string Notification_Delete_Success {
            get {
                return ResourceManager.GetString("Notification.Delete.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications retrieved successfully..
        /// </summary>
        public static string Notification_GetAll_Success {
            get {
                return ResourceManager.GetString("Notification.GetAll.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification retrieved successfully..
        /// </summary>
        public static string Notification_GetById_Success {
            get {
                return ResourceManager.GetString("Notification.GetById.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread notifications retrieved successfully..
        /// </summary>
        public static string Notification_GetUnread_Success {
            get {
                return ResourceManager.GetString("Notification.GetUnread.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread count retrieved successfully..
        /// </summary>
        public static string Notification_GetUnreadCount_Success {
            get {
                return ResourceManager.GetString("Notification.GetUnreadCount.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All notifications marked as read..
        /// </summary>
        public static string Notification_MarkAllAsRead_Success {
            get {
                return ResourceManager.GetString("Notification.MarkAllAsRead.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification marked as read..
        /// </summary>
        public static string Notification_MarkAsRead_Success {
            get {
                return ResourceManager.GetString("Notification.MarkAsRead.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification &apos;{0}&apos; not found..
        /// </summary>
        public static string Notification_NotFound {
            get {
                return ResourceManager.GetString("Notification.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform report retrieved successfully..
        /// </summary>
        public static string PlatformReport_Get_Success {
            get {
                return ResourceManager.GetString("PlatformReport.Get.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products by category retrieved successfully..
        /// </summary>
        public static string Product_ByCategory_Success {
            get {
                return ResourceManager.GetString("Product.ByCategory.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product added successfully..
        /// </summary>
        public static string Product_Create_Success {
            get {
                return ResourceManager.GetString("Product.Create.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product deleted successfully..
        /// </summary>
        public static string Product_Delete_Success {
            get {
                return ResourceManager.GetString("Product.Delete.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products retrieved successfully..
        /// </summary>
        public static string Product_GetAll_Success {
            get {
                return ResourceManager.GetString("Product.GetAll.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product retrieved successfully..
        /// </summary>
        public static string Product_GetByName_Success {
            get {
                return ResourceManager.GetString("Product.GetByName.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In stock products retrieved successfully..
        /// </summary>
        public static string Product_InStock_Success {
            get {
                return ResourceManager.GetString("Product.InStock.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low stock products retrieved successfully..
        /// </summary>
        public static string Product_LowStock_Success {
            get {
                return ResourceManager.GetString("Product.LowStock.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low stock products count retrieved successfully..
        /// </summary>
        public static string Product_LowStockCount_Success {
            get {
                return ResourceManager.GetString("Product.LowStockCount.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product &apos;{0}&apos; not found..
        /// </summary>
        public static string Product_NotFound {
            get {
                return ResourceManager.GetString("Product.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of stock products retrieved successfully..
        /// </summary>
        public static string Product_OutOfStock_Success {
            get {
                return ResourceManager.GetString("Product.OutOfStock.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top sales products retrieved successfully..
        /// </summary>
        public static string Product_TopSales_Success {
            get {
                return ResourceManager.GetString("Product.TopSales.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product updated successfully..
        /// </summary>
        public static string Product_Update_Success {
            get {
                return ResourceManager.GetString("Product.Update.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger not found..
        /// </summary>
        public static string PublicLedger_NotFound {
            get {
                return ResourceManager.GetString("PublicLedger.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger retrieved..
        /// </summary>
        public static string PublicLedger_Success {
            get {
                return ResourceManager.GetString("PublicLedger.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial report generated successfully..
        /// </summary>
        public static string Reports_Financial_Success {
            get {
                return ResourceManager.GetString("Reports.Financial.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross profit calculated successfully..
        /// </summary>
        public static string Reports_GrossProfit_Success {
            get {
                return ResourceManager.GetString("Reports.GrossProfit.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total expenses calculated successfully..
        /// </summary>
        public static string Reports_TotalExpenses_Success {
            get {
                return ResourceManager.GetString("Reports.TotalExpenses.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must not exceed 200 characters..
        /// </summary>
        public static string Validation_Address_MaxLength {
            get {
                return ResourceManager.GetString("Validation.Address.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must not exceed 250 characters..
        /// </summary>
        public static string Validation_Address_MaxLength250 {
            get {
                return ResourceManager.GetString("Validation.Address.MaxLength250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required..
        /// </summary>
        public static string Validation_Address_Required {
            get {
                return ResourceManager.GetString("Validation.Address.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than zero..
        /// </summary>
        public static string Validation_Amount_GreaterThanZero {
            get {
                return ResourceManager.GetString("Validation.Amount.GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business ID is required..
        /// </summary>
        public static string Validation_BusinessId_Required {
            get {
                return ResourceManager.GetString("Validation.BusinessId.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business name must not exceed 100 characters..
        /// </summary>
        public static string Validation_BusinessName_MaxLength {
            get {
                return ResourceManager.GetString("Validation.BusinessName.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business name must be at least 2 characters..
        /// </summary>
        public static string Validation_BusinessName_MinLength {
            get {
                return ResourceManager.GetString("Validation.BusinessName.MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business name is required..
        /// </summary>
        public static string Validation_BusinessName_Required {
            get {
                return ResourceManager.GetString("Validation.BusinessName.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name must not exceed 100 characters..
        /// </summary>
        public static string Validation_CategoryName_MaxLength {
            get {
                return ResourceManager.GetString("Validation.CategoryName.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is required..
        /// </summary>
        public static string Validation_CategoryName_Required {
            get {
                return ResourceManager.GetString("Validation.CategoryName.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID is required..
        /// </summary>
        public static string Validation_CustomerId_Required {
            get {
                return ResourceManager.GetString("Validation.CustomerId.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Id is required..
        /// </summary>
        public static string Validation_CustomerId_RequiredUpdate {
            get {
                return ResourceManager.GetString("Validation.CustomerId.RequiredUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must not exceed 100 characters..
        /// </summary>
        public static string Validation_CustomerName_MaxLength {
            get {
                return ResourceManager.GetString("Validation.CustomerName.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name is required..
        /// </summary>
        public static string Validation_CustomerName_Required {
            get {
                return ResourceManager.GetString("Validation.CustomerName.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date is required..
        /// </summary>
        public static string Validation_DateFrom_Required {
            get {
                return ResourceManager.GetString("Validation.DateFrom.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date must be greater than or equal to From date..
        /// </summary>
        public static string Validation_DateTo_MustBeAfterFrom {
            get {
                return ResourceManager.GetString("Validation.DateTo.MustBeAfterFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date cannot be a future date..
        /// </summary>
        public static string Validation_DateTo_NotFuture {
            get {
                return ResourceManager.GetString("Validation.DateTo.NotFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date is required..
        /// </summary>
        public static string Validation_DateTo_Required {
            get {
                return ResourceManager.GetString("Validation.DateTo.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid email address is required..
        /// </summary>
        public static string Validation_Email_Invalid {
            get {
                return ResourceManager.GetString("Validation.Email.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must not exceed 200 characters..
        /// </summary>
        public static string Validation_Email_MaxLength {
            get {
                return ResourceManager.GetString("Validation.Email.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Validation_Email_Required {
            get {
                return ResourceManager.GetString("Validation.Email.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than zero..
        /// </summary>
        public static string Validation_Expense_Amount_GreaterThanZero {
            get {
                return ResourceManager.GetString("Validation.Expense.Amount.GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid expense category must be selected..
        /// </summary>
        public static string Validation_Expense_Category_Invalid {
            get {
                return ResourceManager.GetString("Validation.Expense.Category.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must not exceed 150 characters..
        /// </summary>
        public static string Validation_Expense_Title_MaxLength {
            get {
                return ResourceManager.GetString("Validation.Expense.Title.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string Validation_Expense_Title_Required {
            get {
                return ResourceManager.GetString("Validation.Expense.Title.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last visit cannot be a future date..
        /// </summary>
        public static string Validation_LastVisit_NotFuture {
            get {
                return ResourceManager.GetString("Validation.LastVisit.NotFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last visit date is required..
        /// </summary>
        public static string Validation_LastVisit_Required {
            get {
                return ResourceManager.GetString("Validation.LastVisit.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes must not exceed 500 characters..
        /// </summary>
        public static string Validation_Notes_MaxLength {
            get {
                return ResourceManager.GetString("Validation.Notes.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner name must not exceed 100 characters..
        /// </summary>
        public static string Validation_OwnerName_MaxLength {
            get {
                return ResourceManager.GetString("Validation.OwnerName.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner name must be at least 2 characters..
        /// </summary>
        public static string Validation_OwnerName_MinLength {
            get {
                return ResourceManager.GetString("Validation.OwnerName.MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner name is required..
        /// </summary>
        public static string Validation_OwnerName_Required {
            get {
                return ResourceManager.GetString("Validation.OwnerName.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid phone number is required..
        /// </summary>
        public static string Validation_PhoneNumber_Invalid {
            get {
                return ResourceManager.GetString("Validation.PhoneNumber.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be 7-15 digits and may start with &apos;+&apos;..
        /// </summary>
        public static string Validation_PhoneNumber_InvalidGeneric {
            get {
                return ResourceManager.GetString("Validation.PhoneNumber.InvalidGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be a valid Pakistani number, e.g. 0300-1234567 or +923001234567..
        /// </summary>
        public static string Validation_PhoneNumber_InvalidPakistani {
            get {
                return ResourceManager.GetString("Validation.PhoneNumber.InvalidPakistani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must not exceed 11 characters..
        /// </summary>
        public static string Validation_PhoneNumber_MaxLength {
            get {
                return ResourceManager.GetString("Validation.PhoneNumber.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required..
        /// </summary>
        public static string Validation_PhoneNumber_Required {
            get {
                return ResourceManager.GetString("Validation.PhoneNumber.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid subscription plan must be selected..
        /// </summary>
        public static string Validation_Plan_Invalid {
            get {
                return ResourceManager.GetString("Validation.Plan.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is required..
        /// </summary>
        public static string Validation_Product_CategoryId_Required {
            get {
                return ResourceManager.GetString("Validation.Product.CategoryId.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID is required..
        /// </summary>
        public static string Validation_Product_Id_Required {
            get {
                return ResourceManager.GetString("Validation.Product.Id.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name must not exceed 100 characters..
        /// </summary>
        public static string Validation_Product_Name_MaxLength {
            get {
                return ResourceManager.GetString("Validation.Product.Name.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name is required..
        /// </summary>
        public static string Validation_Product_Name_Required {
            get {
                return ResourceManager.GetString("Validation.Product.Name.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than zero..
        /// </summary>
        public static string Validation_Product_Price_GreaterThanZero {
            get {
                return ResourceManager.GetString("Validation.Product.Price.GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is unrealistically high..
        /// </summary>
        public static string Validation_Product_Price_TooHigh {
            get {
                return ResourceManager.GetString("Validation.Product.Price.TooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock cannot be negative..
        /// </summary>
        public static string Validation_Product_Stock_NotNegative {
            get {
                return ResourceManager.GetString("Validation.Product.Stock.NotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sale must have at least one item..
        /// </summary>
        public static string Validation_Sale_Items_Required {
            get {
                return ResourceManager.GetString("Validation.Sale.Items.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid payment status..
        /// </summary>
        public static string Validation_Sale_PaymentStatus_Invalid {
            get {
                return ResourceManager.GetString("Validation.Sale.PaymentStatus.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is required..
        /// </summary>
        public static string Validation_SaleItem_ProductId_Required {
            get {
                return ResourceManager.GetString("Validation.SaleItem.ProductId.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be at least 1..
        /// </summary>
        public static string Validation_SaleItem_Quantity_GreaterThanZero {
            get {
                return ResourceManager.GetString("Validation.SaleItem.Quantity.GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total purchases cannot be negative..
        /// </summary>
        public static string Validation_TotalPurchases_NotNegative {
            get {
                return ResourceManager.GetString("Validation.TotalPurchases.NotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udhar amount cannot be negative..
        /// </summary>
        public static string Validation_UdharAmount_NotNegative {
            get {
                return ResourceManager.GetString("Validation.UdharAmount.NotNegative", resourceCulture);
            }
        }
    }
}
